#!/usr/bin/env python
#coding: utf-8

'''
© Copyright 2013 Altair Engineering, Inc. All rights reserved.
This code is provided “as is” without any warranty, express or implied, or
indemnification of any kind. All other terms and conditions are as specified
in the Altair PBS Analytics EULA.
'''

import os
import sys
import re
import shutil

from optparse import OptionParser
from optparse import OptionGroup

import datetime

__version__ = '12.0.0'

parser = OptionParser(usage='%prog <App_nameName> [Options]',
                      version='%prog ' + __version__,
                      description='A simple framework for creating powerful application definitions.')

resources = OptionGroup(parser, "Resource & Attribute Options",
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.")

resources.add_option('--statement',
                     dest='statement',
                     action='store_true',
                     default=False,
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

resources.add_option('--select',
                     dest='select',
                     action='store_true',
                     default=False,
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

resources.add_option('--ncpus',
                     dest='ncpus',
                     action='store_true',
                     default=False,
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

resources.add_option('--ncpus-lead-node',
                     dest='ncpus_lead_node',
                     action='store_true',
                     default=False,
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

resources.add_option('--ncpus-per-node',
                     dest='ncpus_per_node',
                     action='store_true',
                     default=False,
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

resources.add_option('--mem',
                     dest='mem',
                     action='store_true',
                     default=False,
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

resources.add_option('--mem-lead-node',
                     dest='mem_lead_node',
                     action='store_true',
                     default=False,
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

resources.add_option('--mem-per-node',
                     dest='mem_per_node',
                     action='store_true',
                     default=False,
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

resources.add_option('--walltime',
                     dest='walltime',
                     action='store_true',
                     default=False,
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

resources.add_option('--place',
                     dest='place',
                     action='store_true',
                     default=False,
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

parser.add_option_group(resources)

execution = OptionGroup(parser, "Execution Options",
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.")

execution.add_option('--environment',
                     dest='environment',
                     action='store_true',
                     default=False,
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

execution.add_option('--executable',
                     dest='executable',
                     action='store_true',
                     default=False,
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

execution.add_option('--script',
                     dest='script',
                     action='store_true',
                     default=False,
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

execution.add_option('--arguments',
                     dest='arguments',
                     action='store_true',
                     default=False,
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

parser.add_option_group(execution)

file_handling = OptionGroup(parser, "File Handling Options",
                            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.")

file_handling.add_option('--input-file',
                         dest='input_file',
                         action='store_true',
                         default=False,
                         help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

file_handling.add_option('--include-files',
                         dest='include_files',
                         action='store_true',
                         default=False,
                         help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

file_handling.add_option('--pre-staging',
                         dest='pre_staging',
                         action='store_true',
                         default=False,
                         help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

file_handling.add_option('--compress-results',
                         dest='compress_results',
                         action='store_true',
                         default=False,
                         help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

parser.add_option_group(file_handling)

actions = OptionGroup(parser, "Runtime Action Options",
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.")

actions.add_option('--send-signals',
                   dest='show',
                   action='store_true',
                   default=False,
                   help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

parser.add_option_group(actions)

developer = OptionGroup(parser, "Developer Options",
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.")

developer.add_option('--logging',
                     dest='logging',
                     action='store_true',
                     default=False,
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

developer.add_option('--hook-submittime',
                     dest='hook_submittime',
                     action='store',
                     default='none',
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

developer.add_option('--hook-runtime',
                     dest='hook_runtime',
                     action='store',
                     default='none',
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

developer.add_option('--hook-action',
                     dest='hook_action',
                     action='store',
                     default='none',
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

developer.add_option('--hook-exit',
                     dest='hook_exit',
                     action='store',
                     default='none',
                     help='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin felis id lobortis dictum. Nullam elementum rhoncus nisl ac faucibus. Curabitur et augue vehicula, elementum lacus ornare, adipiscing massa. Maecenas ut massa posuere, consequat felis quis, interdum orci.')

parser.add_option_group(developer)

(options, args) = parser.parse_args()

if len(args) == 1:

    app_name = args[0]

    app_config = os.environ['PAS_APP_CONFIG']
    app_home = os.environ['PAS_APP_HOME']

    app_input = open('%s/app-inp.xml' % (app_config), 'r')
    app_converter = open('%s/app-conv.xml' % (app_config), 'r')

    os.system('mkdir -p %s/%s' % (app_home, app_name))
    os.system('mkdir -p %s/%s/runtime' % (app_home, app_name))
    os.system('mkdir -p %s/%s/submittime' % (app_home, app_name))
    os.system('cp %s/presubmit.py %s/%s/submittime' % (app_config, app_home, app_name))
    os.system('cp %s/start.py %s/%s/runtime' % (app_config, app_home, app_name))
    os.system('cp %s/actions.py %s/%s/runtime' % (app_config, app_home, app_name))

    app_name_input = open('%s/%s/app-inp-%s.xml' % (app_home, app_name, app_name), 'w')
    app_name_converter = open('%s/%s/app-conv-%s.xml' % (app_home, app_name, app_name), 'w')

    ''' Generate Input File '''

    enabled = True

    for line in app_input.readlines():

        line = re.sub('APP_NAME', app_name, line)

        ''' Statement '''

        if re.match('.*PAS_STATEMENT BEGIN', line):

            if options.statement is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_STATEMENT END', line):

            if options.statement is True:
                pass
            else:
                enabled = True

        ''' Select '''

        if re.match('.*PAS_SELECT BEGIN', line):

            if options.select is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_SELECT END', line):

            if options.select is True:
                pass
            else:
                enabled = True

        ''' Ncpus '''

        if re.match('.*PAS_NCPUS BEGIN', line):

            if options.ncpus is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_NCPUS END', line):

            if options.ncpus is True:
                pass
            else:
                enabled = True

        ''' Ncpus Lead Node '''

        if re.match('.*PAS_NCPUS_LEAD_NODE BEGIN', line):

            if options.ncpus_lead_node is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_NCPUS_LEAD_NODE END', line):

            if options.ncpus_lead_node is True:
                pass
            else:
                enabled = True

        ''' Ncpus Per Node '''

        if re.match('.*PAS_NCPUS_PER_NODE BEGIN', line):

            if options.ncpus_per_node is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_NCPUS_PER_NODE END', line):

            if options.ncpus_per_node is True:
                pass
            else:
                enabled = True

        ''' Mem '''

        if re.match('.*PAS_MEM BEGIN', line):

            if options.mem is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_MEM END', line):

            if options.mem is True:
                pass
            else:
                enabled = True

        ''' Mem Lead Node '''

        if re.match('.*PAS_MEM_LEAD_NODE BEGIN', line):

            if options.mem_lead_node is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_MEM_LEAD_NODE END', line):

            if options.mem_lead_node is True:
                pass
            else:
                enabled = True

        ''' Mem Per Node '''

        if re.match('.*PAS_MEM_PER_NODE BEGIN', line):

            if options.mem_per_node is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_MEM_PER_NODE END', line):

            if options.mem_per_node is True:
                pass
            else:
                enabled = True

        ''' Walltime '''

        if re.match('.*PAS_WALLTIME BEGIN', line):

            if options.walltime is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_WALLTIME END', line):

            if options.walltime is True:
                pass
            else:
                enabled = True

        ''' Place '''

        if re.match('.*PAS_PLACE BEGIN', line):

            if options.place is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_PLACE END', line):

            if options.place is True:
                pass
            else:
                enabled = True

        ''' Environment '''

        if re.match('.*PAS_ENVIRONMENT BEGIN', line):

            if options.environment is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_ENVIRONMENT END', line):

            if options.environment is True:
                pass
            else:
                enabled = True

        ''' Executable '''

        if re.match('.*PAS_EXECUTABLE BEGIN', line):

            if options.executable is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_EXECUTABLE END', line):

            if options.executable is True:
                pass
            else:
                enabled = True

        ''' Script '''

        if re.match('.*PAS_SCRIPT BEGIN', line):

            if options.script is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_SCRIPT END', line):

            if options.script is True:
                pass
            else:
                enabled = True

        ''' Arguments '''

        if re.match('.*PAS_ARGUMENTS BEGIN', line):

            if options.arguments is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_ARGUMENTS END', line):

            if options.arguments is True:
                pass
            else:
                enabled = True

        ''' Input File '''

        if re.match('.*PAS_INPUT_FILE BEGIN', line):

            if options.input_file is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_INPUT_FILE END', line):

            if options.input_file is True:
                pass
            else:
                enabled = True

        ''' Include Files '''

        if re.match('.*PAS_INCLUDE_FILES BEGIN', line):

            if options.include_files is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_INCLUDE_FILES END', line):

            if options.include_files is True:
                pass
            else:
                enabled = True

        ''' Pre Staging '''

        if re.match('.*PAS_PRE_STAGING BEGIN', line):

            if options.pre_staging is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_PRE_STAGING END', line):

            if options.pre_staging is True:
                pass
            else:
                enabled = True

        ''' Compress Results '''

        if re.match('.*PAS_COMPRESS_RESULTS BEGIN', line):

            if options.compress_results is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_COMPRESS_RESULTS END', line):

            if options.compress_results is True:
                pass
            else:
                enabled = True

        ''' Logging '''

        if re.match('.*PAS_LOGGING BEGIN', line):

            if options.logging is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_LOGGING END', line):

            if options.logging is True:
                pass
            else:
                enabled = True

        if enabled is True:

            if not re.search('.*<!-- .* -->.*', line):
                app_name_input.write(line)

    ''' Generate Convereter File '''

    enabled = True

    for line in app_converter.readlines():

        line = re.sub('APP_NAME', app_name, line)

        ''' Script '''

        if re.match('.*PAS_SCRIPT BEGIN', line):

            if options.script is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_SCRIPT END', line):

            if options.script is True:
                pass
            else:
                enabled = True

        ''' Input File '''

        if re.match('.*PAS_INPUT_FILE BEGIN', line):

            if options.input_file is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_INPUT_FILE END', line):

            if options.input_file is True:
                pass
            else:
                enabled = True

        ''' Include Files '''

        if re.match('.*PAS_INCLUDE_FILES BEGIN', line):

            if options.include_files is True:
                enabled = True
            else:
                enabled = False

        if re.match('.*PAS_INCLUDE_FILES END', line):

            if options.include_files is True:
                pass
            else:
                enabled = True

        if enabled is True:

            if not re.search('.*<!-- .* -->.*', line):
                app_name_converter.write(line)

    ''' Hook Processing '''

    if not options.hook_submittime == 'none':

        if os.path.exists(options.hook_submittime):
            shutil.copy2(options.hook_submittime, '%s/%s/submittime/submittime.hook' % (app_home, app_name))

    if not options.hook_runtime == 'none':

        if os.path.exists(options.hook_runtime):
            shutil.copy2(options.hook_runtime, '%s/%s/runtime/runtime.hook' % (app_home, app_name))

    if not options.hook_action == 'none':

        if os.path.exists(options.hook_action):
            shutil.copy2(options.hook_action, '%s/%s/runtime/action.hook' % (app_home, app_name))

    if not options.hook_exit == 'none':

        if os.path.exists(options.hook_exit):
            shutil.copy2(options.hook_exit, '%s/%s/runtime/exit.hook' % (app_home, app_name))

    sys.exit(0)

else:

    sys.stderr.write('Incorrect number of arguments. '
                     'Try pas-appmaker --help to learn more.\n')
    sys.exit(1)

